const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.video,
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.LocalStorage,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{персонаж: 0},
	{Спрайт: 0},
	{Тач: 0},
	{Текст: 0},
	{ТайловыйФон: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{Спрайт4: 0},
	{ТайловыйФон2: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{Спрайт7: 0},
	{Спрайт8: 0},
	{статика: 0},
	{Назад: 0},
	{LocalStorage: 0},
	{ТайловыйФон3: 0},
	{НовыйПроект: 0},
	{НовыйПроект2: 0},
	{НовыйПроект3: 0},
	{НовыйПроект4: 0},
	{НовыйПроект5: 0},
	{НовыйПроект6: 0},
	{НовыйПроект7: 0},
	{НовыйПроект8: 0},
	{монеты: 0}
];

self.InstanceType = {
	персонаж: class extends self.IWorldInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	Текст: class extends self.ITextInstance {},
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	статика: class extends self.IWorldInstance {},
	Назад: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	НовыйПроект: class extends self.ISpriteInstance {},
	НовыйПроект2: class extends self.ISpriteInstance {},
	НовыйПроект3: class extends self.ISpriteInstance {},
	НовыйПроект4: class extends self.ISpriteInstance {},
	НовыйПроект5: class extends self.ISpriteInstance {},
	НовыйПроект6: class extends self.ISpriteInstance {},
	НовыйПроект7: class extends self.ISpriteInstance {},
	НовыйПроект8: class extends self.ISpriteInstance {}
}